### PR TITLE
Top bar clickable position improved and right side selection effect an…

### PR DESCRIPTION
**Pull request by janealam007**
…d selection cursor changed to a hand icon and cross icon modified.

### CODE REVIEW

**Comment by niiloArction** [comment]
I like it! Especially the panel on right looks much nicer. Good job.

I don't personally like the top bar. It seems super thick now.

**Comment by niiloArction** [comment]
Some issues:

1. Effect remove button no longer aligns with module remove buttons.

image

2. Work in progress popup is no longer fully visible.

image

**Comment by niiloArction** [comment]
This pull request also removes .github and .vscode folders for some reason. These are preeetty important and should not be removed!

**Comment by Nipatsku** [comment]
@janealam007 Synchronized with master

**Review by Nipatsku — APPROVED** [review]

**Pull request merged**
